apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://your-git-repository-url.git'
    path: '/'  # Points to the root of the repo
    targetRevision: HEAD  # You can pin this to a specific branch, tag, or commit
    directory:
      recurse: true  # Recurse into directories to find Kubernetes manifests
      jsonnet: {}  # If your Argo CD instance supports Jsonnet directly
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}  # Enables automatic syncing
    # Add additional sync policy settings as needed