replicaCount: 1

image:
  repository: https://github.com/kubernetes/ingress-nginx
  pullPolicy: IfNotPresent
  tag: "1.9.3" # Use the same version as appVersion in Chart.yaml, or adapt as needed

service:
  type: ClusterIP
  port: 80

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
